version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.0.10
    - 13.0.13
    - 13.0.16
    - 13.0.7
    - 13.1.1
    - 13.1.2
    - 13.1.3
    - 13.1.5
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.12
  - dependency-name: husky
    versions:
    - 5.2.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
  - dependency-name: semver
    versions:
    - 7.3.4
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: lint-staged
    versions:
    - 10.5.3
    - 10.5.4
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.10
    - 7.12.13
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.5
  - dependency-name: standard
    versions:
    - 16.0.3
